/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Graphic;

import javax.swing.ImageIcon;

/**
 *
 * @author andres
 */
public class About extends javax.swing.JFrame {

    /**
     * Creates new form About
     */
    public About() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/Resources/Spartan.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("H.A-About");
        setMinimumSize(new java.awt.Dimension(920, 562));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Name.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(680, 0, 240, 67);

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(java.awt.SystemColor.controlDkShadow);
        jTextArea1.setColumns(20);
        jTextArea1.setForeground(new java.awt.Color(204, 204, 204));
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("Sinopsis : \n\nEn la era del gran herodes un supuesto mesías descendió del cielo,profetizando un modelo de vida impositor a las masas del antiguo imperio \nromano,aquel descendido profeta se encargaba de dogmatizar a todo aquello que produjera sombra, provocando guerras dentro de lo que \nfue la gran Roma, ante esta amenaza el imperio romano no se quedó con los brazos cruzados y decidió salir en busca de aquel colonizador,\ntras muchas horas de combate contras sus más fieles seguidores el falso profeta fue desterrado de la tierra, pero no antes de jurar venganza\ny dominio sobre la faz de la tierra.\n\n2 milenios después aquel “profeta” había descendido de nuevo del cielo (tal como lo predicen las sagradas escrituras), pero esta vez no estaba solo, venía con un millar de ejércitos entre armas y cantos de guerra por el dominio de la tierra,las principales agencias de inteligencia del G8  desconocían la situación, por el contrario la veían venir basándose en sus recopilaciones históricas. Por lo que están listos para que las máquinas liberen su batalla y de esta manera dar el siguiente mensaje a las deidades: “Ni dioses, ni reyes, solo hombres”.\n\n\n\nEspecificaciones\nGénero: Action,  RPG.\nEdad recomendada: 14 años.\n\n\nTiempo : 5 a.C y época contemporánea (2020 d.c)\nEspacio: Cielo abierto y fuera de la atmósfera terrestre.\nDuración: 3-4, escenas. \n\n\nPersonajes:\nRobots “Heroes”:\n\n\nRobot cazador: Avión Caza.\nRobot hechicero: Astronave con armamento químico, altamente aturdidor para las tropas divinas.\nRobot guerrero: Máquina de forma humanoide con armamento militar.\n\n\nDeidades:\nHades\nCerberus\nBaphomet\nRa\nAnubis\nJesus\nVishnu\nArcangel\nVassago\nLilith\nUcrunius\nGanesha\nBeleth\nBifrons\nEmma-o\nMarduk\nSet\n");
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.setBorder(null);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 140, 920, 410);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Lab.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 160, 110);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/By.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 110, 90, 30);

        jButton1.setText("Return");
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(820, 105, 80, 20);

        jLabel4.setBackground(java.awt.SystemColor.controlDkShadow);
        jLabel4.setOpaque(true);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 920, 150);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(About.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(About.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(About.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(About.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new About().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
