package Graphic;


import javax.swing.ImageIcon;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author andres
 */
public class BattlefieldUI extends javax.swing.JFrame {

    /**
     * Creates new form BattlefieldUI
     */
    public BattlefieldUI() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/Resources/Battle.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        Enemy1 = new javax.swing.JMenuItem();
        Enemy2 = new javax.swing.JMenuItem();
        Enemy3 = new javax.swing.JMenuItem();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        Heal = new javax.swing.JMenuItem();
        Defend = new javax.swing.JMenuItem();
        SpecialAttack = new javax.swing.JMenuItem();
        Health = new javax.swing.JMenuItem();
        Agility = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jProgressBar1 = new javax.swing.JProgressBar();
        jProgressBar2 = new javax.swing.JProgressBar();
        jProgressBar3 = new javax.swing.JProgressBar();
        jProgressBar4 = new javax.swing.JProgressBar();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        Enemy1.setText("jMenuItem1");
        jPopupMenu1.add(Enemy1);

        Enemy2.setText("jMenuItem1");
        jPopupMenu1.add(Enemy2);

        Enemy3.setText("jMenuItem1");
        jPopupMenu1.add(Enemy3);

        Heal.setText("jMenuItem1");
        jPopupMenu2.add(Heal);

        Defend.setText("jMenuItem1");
        jPopupMenu2.add(Defend);

        SpecialAttack.setText("jMenuItem1");
        jPopupMenu2.add(SpecialAttack);

        Health.setText("jMenuItem1");
        jPopupMenu2.add(Health);

        Agility.setText("jMenuItem1");
        jPopupMenu2.add(Agility);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("H.A-Battlefield");
        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setPreferredSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 102, 102)));
        jPanel1.setMaximumSize(new java.awt.Dimension(1280, 32767));
        jPanel1.setLayout(null);

        jTextField1.setBackground(java.awt.SystemColor.controlDkShadow);
        jTextField1.setFont(new java.awt.Font("Draggle BRK", 0, 14)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(204, 204, 204));
        jTextField1.setText("Hp");
        jTextField1.setBorder(null);
        jPanel1.add(jTextField1);
        jTextField1.setBounds(136, 78, 19, 22);
        jPanel1.add(jProgressBar1);
        jProgressBar1.setBounds(13, 86, 117, 14);
        jPanel1.add(jProgressBar2);
        jProgressBar2.setBounds(13, 158, 117, 14);
        jPanel1.add(jProgressBar3);
        jProgressBar3.setBounds(13, 118, 117, 14);
        jPanel1.add(jProgressBar4);
        jProgressBar4.setBounds(13, 196, 117, 14);

        jTextField2.setEditable(false);
        jTextField2.setBackground(java.awt.SystemColor.controlDkShadow);
        jTextField2.setFont(new java.awt.Font("DkgHandwriting", 0, 24)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(204, 204, 204));
        jTextField2.setText("Stats");
        jTextField2.setBorder(null);
        jPanel1.add(jTextField2);
        jTextField2.setBounds(13, 21, 59, 59);

        jTextField3.setBackground(java.awt.SystemColor.controlDkShadow);
        jTextField3.setFont(new java.awt.Font("Draggle over kerned BRK", 0, 14)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(204, 204, 204));
        jTextField3.setText("Agility");
        jTextField3.setBorder(null);
        jPanel1.add(jTextField3);
        jTextField3.setBounds(136, 118, 49, 22);

        jTextField4.setBackground(java.awt.SystemColor.controlDkShadow);
        jTextField4.setFont(new java.awt.Font("Draggle over kerned BRK", 0, 14)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(204, 204, 204));
        jTextField4.setText("Defense");
        jTextField4.setBorder(null);
        jPanel1.add(jTextField4);
        jTextField4.setBounds(136, 150, 60, 22);

        jTextField5.setBackground(java.awt.SystemColor.controlDkShadow);
        jTextField5.setFont(new java.awt.Font("Draggle over kerned BRK", 0, 14)); // NOI18N
        jTextField5.setForeground(new java.awt.Color(204, 204, 204));
        jTextField5.setText("Damage");
        jTextField5.setBorder(null);
        jPanel1.add(jTextField5);
        jTextField5.setBounds(136, 196, 56, 22);

        jTextField6.setEditable(false);
        jTextField6.setBackground(java.awt.SystemColor.controlDkShadow);
        jTextField6.setFont(new java.awt.Font("DkgHandwriting", 0, 24)); // NOI18N
        jTextField6.setForeground(new java.awt.Color(204, 204, 204));
        jTextField6.setText("Actions");
        jTextField6.setBorder(null);
        jPanel1.add(jTextField6);
        jTextField6.setBounds(13, 298, 72, 59);

        jButton2.setText("Run");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(13, 387, 93, 25);

        jButton3.setText("Skill");
        jButton3.setComponentPopupMenu(jPopupMenu2);
        jPanel1.add(jButton3);
        jButton3.setBounds(13, 444, 93, 25);

        jButton10.setText("Map");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton10);
        jButton10.setBounds(13, 502, 93, 25);

        jLabel2.setBackground(java.awt.SystemColor.controlDkShadow);
        jLabel2.setOpaque(true);
        jPanel1.add(jLabel2);
        jLabel2.setBounds(1, 1, 230, 720);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(1070, 0, 210, 720);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/R3.png"))); // NOI18N
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        getContentPane().add(jButton4);
        jButton4.setBounds(540, 250, 120, 138);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/E5.png"))); // NOI18N
        jButton5.setBorderPainted(false);
        jButton5.setContentAreaFilled(false);
        getContentPane().add(jButton5);
        jButton5.setBounds(60, 80, 90, 160);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/E7.png"))); // NOI18N
        jButton6.setBorderPainted(false);
        jButton6.setContentAreaFilled(false);
        getContentPane().add(jButton6);
        jButton6.setBounds(280, 360, 100, 140);

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/E8.png"))); // NOI18N
        jButton7.setBorderPainted(false);
        jButton7.setContentAreaFilled(false);
        getContentPane().add(jButton7);
        jButton7.setBounds(70, 570, 50, 130);

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/R1.png"))); // NOI18N
        jButton8.setBorderPainted(false);
        jButton8.setContentAreaFilled(false);
        getContentPane().add(jButton8);
        jButton8.setBounds(810, 540, 100, 140);

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/R2.png"))); // NOI18N
        jButton9.setBorderPainted(false);
        jButton9.setContentAreaFilled(false);
        getContentPane().add(jButton9);
        jButton9.setBounds(860, 90, 70, 150);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/battlefield.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1070, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**
 * Este metodo sera utilizado por el usuario para salir de batalla sin acabarla
 * @param evt 
 */
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        System.out.println("You've abandoned the battle, now you must start again");
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton10ActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BattlefieldUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BattlefieldUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BattlefieldUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BattlefieldUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new BattlefieldUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Agility;
    private javax.swing.JMenuItem Defend;
    private javax.swing.JMenuItem Enemy1;
    private javax.swing.JMenuItem Enemy2;
    private javax.swing.JMenuItem Enemy3;
    private javax.swing.JMenuItem Heal;
    private javax.swing.JMenuItem Health;
    private javax.swing.JMenuItem SpecialAttack;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JProgressBar jProgressBar2;
    private javax.swing.JProgressBar jProgressBar3;
    private javax.swing.JProgressBar jProgressBar4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
