package Graphic;


import javax.swing.ImageIcon;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author andres
 */
public class Bestiary extends javax.swing.JFrame {

    /**
     * Creates new form Bestiary
     */
    /**
     * Con SetIcon se creara un icono para el frame
     */
    public Bestiary() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/Resources/Fire.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("H.A-Bestiary");
        setBackground(java.awt.SystemColor.activeCaptionText);
        setMinimumSize(new java.awt.Dimension(1003, 625));
        setName("Bestiary"); // NOI18N
        setResizable(false);
        getContentPane().setLayout(null);

        jTextField2.setEditable(false);
        jTextField2.setBackground(java.awt.SystemColor.controlDkShadow);
        jTextField2.setFont(new java.awt.Font("DkgHandwriting", 0, 18)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(204, 204, 204));
        jTextField2.setText("Heroes");
        jTextField2.setBorder(null);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(12, 434, 218, 45);

        jTextField3.setEditable(false);
        jTextField3.setBackground(java.awt.SystemColor.controlDkShadow);
        jTextField3.setFont(new java.awt.Font("DkgHandwriting", 0, 18)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(204, 204, 204));
        jTextField3.setText("Enemies");
        jTextField3.setBorder(null);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(12, 34, 218, 45);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/E1.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 90, 128, 128);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/R1.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(170, 470, 128, 128);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/R3.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(570, 460, 128, 128);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/E10.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(150, 90, 128, 128);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/E11.png"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(660, 90, 128, 128);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/E15.png"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(870, 90, 128, 128);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/R2.png"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(380, 460, 128, 128);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/E4.png"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(210, 250, 128, 128);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/E6.png"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(770, 90, 128, 128);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/E5.png"))); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(20, 250, 128, 128);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/E3.png"))); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(390, 80, 128, 128);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/E7.png"))); // NOI18N
        getContentPane().add(jLabel12);
        jLabel12.setBounds(260, 90, 128, 128);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/E8.png"))); // NOI18N
        getContentPane().add(jLabel13);
        jLabel13.setBounds(110, 250, 128, 128);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/E9.png"))); // NOI18N
        getContentPane().add(jLabel14);
        jLabel14.setBounds(510, 90, 128, 128);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/E2.png"))); // NOI18N
        getContentPane().add(jLabel16);
        jLabel16.setBounds(640, 240, 128, 128);

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/2.png"))); // NOI18N
        getContentPane().add(jLabel17);
        jLabel17.setBounds(340, 260, 100, 100);

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/E12.png"))); // NOI18N
        getContentPane().add(jLabel18);
        jLabel18.setBounds(420, 230, 128, 128);

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/E13.png"))); // NOI18N
        getContentPane().add(jLabel19);
        jLabel19.setBounds(530, 240, 128, 128);

        jButton1.setText("Menu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(894, 20, 80, 25);

        jLabel15.setBackground(java.awt.SystemColor.controlDkShadow);
        jLabel15.setOpaque(true);
        getContentPane().add(jLabel15);
        jLabel15.setBounds(0, -5, 1000, 620);

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**
 * Con este metodo se retornara al mapa
 * @param evt 
 */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
              
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bestiary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bestiary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bestiary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bestiary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Bestiary().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
