/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Graphic;

import Logic.MapLogic;
import java.awt.event.KeyEvent;
import javax.swing.ImageIcon;

/**
 *
 * @author andres
 */
public class Map extends javax.swing.JFrame {

    private final MapLogic map;

    /**
     * Creates new form Map
     */
    public Map() {
        initComponents();
        map = new MapLogic();
        setIconImage(new ImageIcon(getClass().getResource("/Resources/Spartan.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("H.A-Map");
        setMaximumSize(new java.awt.Dimension(800, 743));
        setMinimumSize(new java.awt.Dimension(800, 743));
        setPreferredSize(new java.awt.Dimension(800, 743));
        setResizable(false);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setMaximumSize(new java.awt.Dimension(980, 739));
        jPanel1.setMinimumSize(new java.awt.Dimension(980, 739));
        jPanel1.setPreferredSize(new java.awt.Dimension(980, 739));
        jPanel1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPanel1KeyPressed(evt);
            }
        });
        jPanel1.setLayout(new java.awt.GridLayout(8, 8));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/3.png"))); // NOI18N
        jPanel1.add(jLabel1);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/0.png"))); // NOI18N
        jPanel1.add(jLabel2);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/0.png"))); // NOI18N
        jPanel1.add(jLabel3);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/1.png"))); // NOI18N
        jPanel1.add(jLabel4);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/5.png"))); // NOI18N
        jPanel1.add(jLabel5);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/5.png"))); // NOI18N
        jPanel1.add(jLabel6);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/5.png"))); // NOI18N
        jPanel1.add(jLabel7);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/3.png"))); // NOI18N
        jPanel1.add(jLabel8);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/5.png"))); // NOI18N
        jPanel1.add(jLabel9);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/5.png"))); // NOI18N
        jPanel1.add(jLabel10);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/5.png"))); // NOI18N
        jPanel1.add(jLabel11);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/0.png"))); // NOI18N
        jPanel1.add(jLabel12);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/0.png"))); // NOI18N
        jPanel1.add(jLabel13);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/M11.png"))); // NOI18N
        jPanel1.add(jLabel14);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/0.png"))); // NOI18N
        jPanel1.add(jLabel15);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/0.png"))); // NOI18N
        jPanel1.add(jLabel16);

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/0.png"))); // NOI18N
        jPanel1.add(jLabel17);

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/0.png"))); // NOI18N
        jPanel1.add(jLabel18);

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/3.png"))); // NOI18N
        jPanel1.add(jLabel19);

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/5.png"))); // NOI18N
        jPanel1.add(jLabel20);

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/5.png"))); // NOI18N
        jPanel1.add(jLabel21);

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/5.png"))); // NOI18N
        jPanel1.add(jLabel22);

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/0.png"))); // NOI18N
        jPanel1.add(jLabel23);

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/5.png"))); // NOI18N
        jPanel1.add(jLabel24);

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/M2.png"))); // NOI18N
        jPanel1.add(jLabel25);

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/5.png"))); // NOI18N
        jPanel1.add(jLabel26);

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/0.png"))); // NOI18N
        jPanel1.add(jLabel27);

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/0.png"))); // NOI18N
        jPanel1.add(jLabel28);

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/M4.png"))); // NOI18N
        jPanel1.add(jLabel29);

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/0.png"))); // NOI18N
        jPanel1.add(jLabel30);

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/0.png"))); // NOI18N
        jPanel1.add(jLabel31);

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/5.png"))); // NOI18N
        jPanel1.add(jLabel32);

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/0.png"))); // NOI18N
        jPanel1.add(jLabel33);

        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/0.png"))); // NOI18N
        jPanel1.add(jLabel34);

        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/5.png"))); // NOI18N
        jLabel35.setOpaque(true);
        jPanel1.add(jLabel35);

        jLabel36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/5.png"))); // NOI18N
        jPanel1.add(jLabel36);

        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/5.png"))); // NOI18N
        jPanel1.add(jLabel37);

        jLabel38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/5.png"))); // NOI18N
        jPanel1.add(jLabel38);

        jLabel39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/5.png"))); // NOI18N
        jPanel1.add(jLabel39);

        jLabel40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/5.png"))); // NOI18N
        jPanel1.add(jLabel40);

        jLabel41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/5.png"))); // NOI18N
        jPanel1.add(jLabel41);

        jLabel42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/0.png"))); // NOI18N
        jPanel1.add(jLabel42);

        jLabel43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/0.png"))); // NOI18N
        jPanel1.add(jLabel43);

        jLabel44.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/0.png"))); // NOI18N
        jPanel1.add(jLabel44);

        jLabel45.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/0.png"))); // NOI18N
        jPanel1.add(jLabel45);

        jLabel46.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/M5.png"))); // NOI18N
        jPanel1.add(jLabel46);

        jLabel47.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/0.png"))); // NOI18N
        jPanel1.add(jLabel47);

        jLabel48.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/0.png"))); // NOI18N
        jPanel1.add(jLabel48);

        jLabel49.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/M10.png"))); // NOI18N
        jPanel1.add(jLabel49);

        jLabel50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/5.png"))); // NOI18N
        jPanel1.add(jLabel50);

        jLabel51.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/3.png"))); // NOI18N
        jPanel1.add(jLabel51);

        jLabel52.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/5.png"))); // NOI18N
        jPanel1.add(jLabel52);

        jLabel53.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/5.png"))); // NOI18N
        jPanel1.add(jLabel53);

        jLabel54.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/5.png"))); // NOI18N
        jPanel1.add(jLabel54);

        jLabel55.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/5.png"))); // NOI18N
        jPanel1.add(jLabel55);

        jLabel56.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/0.png"))); // NOI18N
        jPanel1.add(jLabel56);

        jLabel57.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/3.png"))); // NOI18N
        jPanel1.add(jLabel57);

        jLabel58.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/0.png"))); // NOI18N
        jPanel1.add(jLabel58);

        jLabel59.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/0.png"))); // NOI18N
        jPanel1.add(jLabel59);

        jLabel60.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/0.png"))); // NOI18N
        jPanel1.add(jLabel60);

        jLabel61.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/0.png"))); // NOI18N
        jPanel1.add(jLabel61);

        jLabel62.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/0.png"))); // NOI18N
        jPanel1.add(jLabel62);

        jLabel63.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/3.png"))); // NOI18N
        jPanel1.add(jLabel63);

        jLabel64.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/0.png"))); // NOI18N
        jPanel1.add(jLabel64);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 800, 740);

        pack();
    }// </editor-fold>//GEN-END:initComponents

//    private void dibujar() {
//        int[][] mapa = map.getMap();
//
//        //pintamos la primera fila
//        jLabel1.setIcon(new ImageIcon(getClass().getResource("/recursos/"
//                + mapa[0][0] + ".png")));
//        jLabel2.setIcon(new ImageIcon(getClass().getResource("/recursos/"
//                + mapa[0][1] + ".png")));
//        jLabel3.setIcon(new ImageIcon(getClass().getResource("/recursos/"
//                + mapa[0][2] + ".png")));
//        jLabel4.setIcon(new ImageIcon(getClass().getResource("/recursos/"
//                + mapa[0][3] + ".png")));
//        jLabel5.setIcon(new ImageIcon(getClass().getResource("/recursos/"
//                + mapa[0][4] + ".png")));
//        jLabel6.setIcon(new ImageIcon(getClass().getResource("/recursos/"
//                + mapa[0][5] + ".png")));
//        jLabel7.setIcon(new ImageIcon(getClass().getResource("/recursos/"
//                + mapa[0][6] + ".png")));
//        jLabel8.setIcon(new ImageIcon(getClass().getResource("/recursos/"
//                + mapa[0][7] + ".png")));
//        //pintamos la primera fila
//        jLabel9.setIcon(new ImageIcon(getClass().getResource("/recursos/"
//                + mapa[1][0] + ".png")));
//        jLabel10.setIcon(new ImageIcon(getClass().getResource("/recursos/"
//                + mapa[1][1] + ".png")));
//        jLabel11.setIcon(new ImageIcon(getClass().getResource("/recursos/"
//                + mapa[1][2] + ".png")));
//        jLabel12.setIcon(new ImageIcon(getClass().getResource("/recursos/"
//                + mapa[1][3] + ".png")));
//        jLabel13.setIcon(new ImageIcon(getClass().getResource("/recursos/"
//                + mapa[1][4] + ".png")));
//        jLabel14.setIcon(new ImageIcon(getClass().getResource("/recursos/"
//                + mapa[1][5] + ".png")));
//        jLabel15.setIcon(new ImageIcon(getClass().getResource("/recursos/"
//                + mapa[1][6] + ".png")));
//        jLabel16.setIcon(new ImageIcon(getClass().getResource("/recursos/"
//                + mapa[1][7] + ".png")));
//    }

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:
        map.getMap();
        switch (evt.getKeyCode()) {

            case KeyEvent.VK_RIGHT:
                System.out.println("Right's been pressed");
                map.moveRight();
                map.verificar();
                map.getMap();
                //dibujar();
                break;
            case KeyEvent.VK_LEFT:
                System.out.println("Left's been pressed");
                map.moveLeft();
                map.verificar();
                map.getMap();
                //dibujar();
                break;
            case KeyEvent.VK_DOWN:
                System.out.println("Down's been pressed");
                map.moveDown();
                map.verificar();
                map.getMap();
                //dibujar();
                break;
            case KeyEvent.VK_UP:
                System.out.println("Up's been pressed");
                map.moveUp();
                map.verificar();
                map.getMap();
                //dibujar();
                break;
            default:
                break;
        }
    }//GEN-LAST:event_formKeyPressed

    private void jPanel1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPanel1KeyPressed

    }//GEN-LAST:event_jPanel1KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Map.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Map.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Map.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Map.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Map().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
